apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  containers:
    - name: frontend
      image: centkanayo10/frontend:2.1.0
      ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend-svc
spec:
  selector:
    name: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
