apiVersion: v1
kind: Pod
metadata:
  name: backend-svc
  labels:
    name: backend-svc
spec:
  containers:
    - name: backend-svc
      image: centkanayo10/backend:1.1.1
      ports:
        - containerPort: 3500

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: backend-svc
  name: backend-svc
spec:
  selector:
    name: backend-svc
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
  type: ClusterIP
