apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-svc
spec:
  selector:
    matchLabels:
      app: backend-svc
  template:
    metadata:
      labels:
        app: backend-svc
    spec:
      containers:
        - name: backend-svc
          image: centkanayo10/backend:1.1.1
          ports:
            - containerPort: 3500

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-svc
  ports:
    - port: 3500
