apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-svc
spec:
  selector:
    matchLabels:
      app: frontend-svc
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      containers:
        - name: frontend-svc
          image: centkanayo10/frontend:2.1.0
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend-svc
  ports:
    - port: 3000
      targetPort: 3000
